### ISSUE TITLE
"View Responses" Link does not show HMRC message after upgrading to 4.6

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.giftaidonline#35]

**Comment by veda-consulting** [comment]
@tapashdatta can you provide some screenshots etc of what your seeing please.

**Comment by tapashdatta** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5366545/8498593/9eeeab84-2180-11e5-8166-bed43656bf70.png)

**Comment by veda-consulting** [comment]
@tapashdatta thanks for the info. Did you submit the batch using the latest version or was it submitted before? What happens when you press view response? Are you seeing any Javascript failures?

**Comment by tapashdatta** [comment]
This batch was submitted on civicrm 4.4 on GAonline 1.7.1 and I was getting the responses.

Not seeing any message since upgraded to 4.6 recently.

3 warning is showing on safari  inspect element 
[Error] TypeError: undefined is not a function (evaluating '$(window).on')
	(anonymous function) (js_YJvzJzgIG3nDMv6spBdAhtIcSgmMgKT5VbBgN8e79JI.js, line 593)
	global code (js_YJvzJzgIG3nDMv6spBdAhtIcSgmMgKT5VbBgN8e79JI.js, line 600)
[Error] TypeError: undefined is not a function (evaluating '$('body').on')
	(anonymous function) (js_YJvzJzgIG3nDMv6spBdAhtIcSgmMgKT5VbBgN8e79JI.js, line 283)
	ready (js_xAPl0qIk9eowy_iS9tNkCWXLUVoat94SQT48UBCFkyQ.js, line 30)
	u (js_xAPl0qIk9eowy_iS9tNkCWXLUVoat94SQT48UBCFkyQ.js, line 38)
[Error] TypeError:  is not a valid argument for 'in' (evaluating '"length" in obj')
	isArraylike (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 1518)
	map (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 1438)
	_fnFilterCreateSearch (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 48712)
	_fnFilter (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 48648)
	_fnFilterComplete (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 48550)
	_fnReDraw (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 47802)
	_fnInitialise (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 48992)
	(anonymous function) (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 52218)
	each (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 1325)
	each (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 1077)
	DataTable (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 51754)
	(anonymous function) (onlinesubmission, line 510)
	fire (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 4089)
	fireWith (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 4201)
	ready (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 4413)
	completed (js_v67v8Ku2d0JthWz2eHz4IqM8zNcFzQ4A9-AjkcGgBAw.js, line 4444)

**Comment by mattwire** [comment]
@tapashdatta @veda-consulting As this issue is now over 3 years old I assume it is no longer a problem and can be closed?
